# Generated by Django 4.2.16 on 2024-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
