# Generated by Django 4.2.16 on 2024-12-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_dj', '0008_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
