# Generated by Django 4.2.16 on 2024-12-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_dj', '0013_order_cart_alter_cart_user_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop_dj.product'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('cart', 'product')},
        ),
    ]
