# Generated by Django 4.2.16 on 2024-12-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_dj', '0026_remove_order_name_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='Не указано', max_length=255),
        ),
    ]
